server:
  port: 9527

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小
  data:
    mongodb:
      authentication-database: admin
      host: 101.200.157.120
      port: 27017
      database: magictable
      username: admin
      password: "@WSX1qaz"
  datasource:
    url: jdbc:mysql://101.200.157.120/magictable
    username: root
    password: "@WSX1qaz"
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
# 拦截器相关的配置
interceptors:
  # 不需要进行鉴权的接口地址，用逗号隔开
  auth-ignore-uris: ${server.servlet.context-path}/user/register,${server.servlet.context-path}/user/login
