server:
  port: 9527

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小
  data:
    mongodb:
      authentication-database: admin
      host: 192.168.56.103
      port: 27017
      database: magictable
      username: admin
      password: tooldev

# 拦截器相关的配置
interceptors:
  # 不需要进行鉴权的接口地址，用逗号隔开
  auth-ignore-uris: ${server.servlet.context-path}/user/register,${server.servlet.context-path}/user/login

